# Generated by Django 5.2 on 2025-06-13 00:21

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="created_at",
            field=api.models.DateTimeNoTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="updated_at",
            field=api.models.DateTimeNoTZField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userlogin",
            name="login_time",
            field=api.models.DateTimeNoTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="last_used",
            field=api.models.DateTimeNoTZField(auto_now=True),
        ),
    ]
