# Generated by Django 5.2 on 2025-06-13 00:29

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_useraccount_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                ("user_event_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                (
                    "date_type",
                    models.CharField(
                        choices=[("GENERIC", "Generic"), ("SPECIFIC", "Specific")],
                        max_length=20,
                    ),
                ),
                ("duration", models.PositiveSmallIntegerField(null=True)),
                ("created_at", api.models.DateTimeNoTZField(auto_now_add=True)),
                ("updated_at", api.models.DateTimeNoTZField(auto_now=True)),
                (
                    "user_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="api.useraccount",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user_account"], name="api_usereve_user_ac_cff53f_idx"
                    )
                ],
            },
        ),
    ]
