# Generated by Django 5.2 on 2025-06-13 02:01

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_userevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDateTimeslot",
            fields=[
                (
                    "event_date_timeslot_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("timeslot", api.models.DateTimeNoTZField()),
                (
                    "user_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_timeslots",
                        to="api.userevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventParticipant",
            fields=[
                (
                    "event_participant_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("display_name", models.CharField(max_length=25, null=True)),
                (
                    "user_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_participated",
                        to="api.useraccount",
                    ),
                ),
                (
                    "user_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="api.userevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventDateAvailability",
            fields=[
                (
                    "event_date_availability_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("is_available", models.BooleanField()),
                (
                    "event_date_timeslot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_availabilities",
                        to="api.eventdatetimeslot",
                    ),
                ),
                (
                    "event_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_date_availabilities",
                        to="api.eventparticipant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventWeekdayTimeslot",
            fields=[
                (
                    "event_weekday_timeslot_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("weekday", models.PositiveSmallIntegerField()),
                ("timeslot", models.TimeField()),
                (
                    "user_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekday_timeslots",
                        to="api.userevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventWeekdayAvailability",
            fields=[
                (
                    "event_weekday_availability_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("is_available", models.BooleanField()),
                (
                    "event_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_weekday_availabilities",
                        to="api.eventparticipant",
                    ),
                ),
                (
                    "event_weekday_timeslot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_availabilities",
                        to="api.eventweekdaytimeslot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UrlCode",
            fields=[
                (
                    "url_code",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("last_used", api.models.DateTimeNoTZField(auto_now=True)),
                (
                    "user_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="url_codes",
                        to="api.userevent",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserLogin",
        ),
    ]
