# Generated by Django 5.2 on 2025-06-13 02:01

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_eventdatetimeslot_eventparticipant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLogin",
            fields=[
                ("user_login_id", models.AutoField(primary_key=True, serialize=False)),
                ("login_time", api.models.DateTimeNoTZField(auto_now_add=True)),
                (
                    "user_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logins",
                        to="api.useraccount",
                    ),
                ),
            ],
        ),
    ]
