# Generated by Django 5.2 on 2025-07-20 20:33

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_userlogin"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "reset_token",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("created_at", api.models.DateTimeNoTZField(auto_now_add=True)),
                (
                    "user_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to="api.useraccount",
                    ),
                ),
            ],
        ),
    ]
