# Generated by Django 5.2 on 2025-07-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventparticipant",
            name="time_zone",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
