# Generated by Django 5.2 on 2025-07-25 22:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_eventparticipant_time_zone"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnverifiedUserAccount",
            fields=[
                (
                    "verification_code",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("password_hash", models.CharField(max_length=255, null=True)),
                ("created_at", api.models.DateTimeNoTZField(auto_now_add=True)),
            ],
        ),
    ]
