# Generated by Django 5.2 on 2025-07-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_unverifieduseraccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="is_infinite",
            field=models.BooleanField(default=False),
        ),
    ]
