# Generated by Django 5.2 on 2025-07-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_usersession_is_infinite"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["is_infinite", "last_used"],
                name="api_userses_is_infi_063be8_idx",
            ),
        ),
    ]
