# Generated by Django 5.2 on 2025-07-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_usersession_api_userses_is_infi_063be8_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="usersession",
            name="api_userses_is_infi_063be8_idx",
        ),
        migrations.RenameField(
            model_name="usersession",
            old_name="is_infinite",
            new_name="is_extended",
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["is_extended", "last_used"],
                name="api_userses_is_exte_ad78eb_idx",
            ),
        ),
    ]
