# Generated by Django 5.2 on 2025-08-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_usersession_api_userses_is_infi_063be8_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unverifieduseraccount",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="unverifieduseraccount",
            name="password_hash",
            field=models.CharField(max_length=255),
        ),
    ]
