# Generated by Django 5.2 on 2025-08-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_unverifieduseraccount_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userevent",
            name="time_zone",
            field=models.CharField(default="Etc/UTC", max_length=50),
            preserve_default=False,
        ),
    ]
