# Generated by Django 5.2 on 2025-08-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_userevent_time_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventparticipant",
            name="time_zone",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="userevent",
            name="time_zone",
            field=models.CharField(max_length=64),
        ),
    ]
