# Generated by Django 5.2 on 2025-08-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_eventparticipant_time_zone_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="eventdatetimeslot",
            index=models.Index(
                fields=["user_event", "timeslot"], name="api_eventda_user_ev_b362a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventweekdaytimeslot",
            index=models.Index(
                fields=["user_event", "weekday", "timeslot"],
                name="api_eventwe_user_ev_e44655_idx",
            ),
        ),
    ]
