# Generated by Django 5.2 on 2025-09-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_eventdatetimeslot_api_eventda_user_ev_b362a7_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventparticipant",
            name="display_name",
            field=models.CharField(default="John", max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="time_zone",
            field=models.CharField(default="Etc/UTC", max_length=64),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="eventparticipant",
            constraint=models.UniqueConstraint(
                fields=("user_event", "user_account"), name="unique_event_participant"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventparticipant",
            constraint=models.UniqueConstraint(
                fields=("user_event", "display_name"),
                name="unique_display_name_per_event",
            ),
        ),
    ]
