# Generated by Django 5.2 on 2025-09-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_eventparticipant_display_name_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="eventdateavailability",
            constraint=models.UniqueConstraint(
                fields=("event_participant", "event_date_timeslot"),
                name="unique_participant_date_timeslot",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventdatetimeslot",
            constraint=models.UniqueConstraint(
                fields=("user_event", "timeslot"), name="unique_date_timeslot_per_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventweekdayavailability",
            constraint=models.UniqueConstraint(
                fields=("event_participant", "event_weekday_timeslot"),
                name="unique_participant_weekday_timeslot",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventweekdaytimeslot",
            constraint=models.UniqueConstraint(
                fields=("user_event", "weekday", "timeslot"),
                name="unique_weekday_timeslot_per_event",
            ),
        ),
    ]
