# Generated by Django 5.2 on 2025-09-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_eventdateavailability_unique_participant_date_timeslot_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="eventdateavailability",
            index=models.Index(
                fields=["event_participant"], name="api_eventda_event_p_7eed90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventweekdayavailability",
            index=models.Index(
                fields=["event_participant"], name="api_eventwe_event_p_5aa286_idx"
            ),
        ),
    ]
