# Generated by Django 5.2 on 2025-10-18 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_eventdateavailability_api_eventda_event_p_7eed90_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlcode',
            name='user_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='url_codes', to='api.userevent'),
        ),
    ]
