# Generated by Django 5.2 on 2025-12-27 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_urlcode_user_event"),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                apps.get_model("api", "EventDateAvailability")
                .objects.filter(is_available=False)
                .delete(),
                apps.get_model("api", "EventWeekdayAvailability")
                .objects.filter(is_available=False)
                .delete(),
            ),
            reverse_code=None,
        ),
        migrations.RemoveField(
            model_name="eventdateavailability",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="eventweekdayavailability",
            name="is_available",
        ),
        migrations.AddField(
            model_name="eventdateavailability",
            name="status",
            field=models.CharField(
                choices=[("AVAILABLE", "Available")], default="AVAILABLE", max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventweekdayavailability",
            name="status",
            field=models.CharField(
                choices=[("AVAILABLE", "Available")], default="AVAILABLE", max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="urlcode",
            name="user_event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="url_code",
                to="api.userevent",
            ),
        ),
    ]
