# Generated by Django 5.2 on 2026-01-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_eventdateavailability_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventdatetimeslot',
            name='unique_date_timeslot_per_event',
        ),
        migrations.RemoveConstraint(
            model_name='eventweekdaytimeslot',
            name='unique_weekday_timeslot_per_event',
        ),
        migrations.RemoveIndex(
            model_name='eventdatetimeslot',
            name='api_eventda_user_ev_b362a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventweekdaytimeslot',
            name='api_eventwe_user_ev_e44655_idx',
        ),
        migrations.RenameField(
            model_name='eventdatetimeslot',
            old_name='timeslot',
            new_name='utc_timeslot',
        ),
        migrations.RenameField(
            model_name='eventweekdaytimeslot',
            old_name='timeslot',
            new_name='local_timeslot',
        ),
        migrations.AddIndex(
            model_name='eventdatetimeslot',
            index=models.Index(fields=['user_event', 'utc_timeslot'], name='api_eventda_user_ev_757977_idx'),
        ),
        migrations.AddIndex(
            model_name='eventweekdaytimeslot',
            index=models.Index(fields=['user_event', 'weekday', 'local_timeslot'], name='api_eventwe_user_ev_6234fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventdatetimeslot',
            constraint=models.UniqueConstraint(fields=('user_event', 'utc_timeslot'), name='unique_date_timeslot_per_event'),
        ),
        migrations.AddConstraint(
            model_name='eventweekdaytimeslot',
            constraint=models.UniqueConstraint(fields=('user_event', 'weekday', 'local_timeslot'), name='unique_weekday_timeslot_per_event'),
        ),
    ]
