# Generated by Django 5.2 on 2026-01-20 02:16

import api.models
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_eventdatetimeslot_unique_date_timeslot_per_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='created_at',
            field=api.models.DateTimeNoTZField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='updated_at',
            field=api.models.DateTimeNoTZField(auto_now=True),
        ),
    ]
