# Generated by Django 5.2 on 2026-01-27 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_eventparticipant_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='display_name',
            new_name='default_display_name',
        ),
    ]
